-- AiroLink POS — automatic product SKU generation.
-- Additive; run after 0005_restrict_helper_execute.sql.
--
-- Reuses the existing org_counters mechanism (the same one that generates receipt
-- numbers): an atomic INSERT ... ON CONFLICT DO UPDATE ... RETURNING against the
-- (org_id, name) primary key. That upsert row-locks, so two concurrent product
-- inserts for the same organization cannot receive the same number — the same
-- guarantee receipt numbering already relies on. No sequence object is needed
-- because the counter is already scoped per organization per name.
--
-- The trigger only fills in NEW.sku when the caller left it null/blank, so:
--  - existing products, which already have a sku, are never touched;
--  - a direct/legacy insert that still supplies its own sku is honoured as-is
--    (and still subject to the existing unique(org_id, sku) constraint);
--  - edits (UPDATE) never pass through this BEFORE INSERT trigger, so a SKU can
--    never be silently regenerated by editing a product.
create function generate_product_sku() returns trigger language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
  if new.sku is null or length(trim(new.sku)) = 0 then
    insert into org_counters(org_id, name, value) values (new.org_id, 'sku', 1)
      on conflict (org_id, name) do update set value = org_counters.value + 1
      returning value into n;
    new.sku := 'PRD-' || lpad(n::text, 6, '0');
  end if;
  return new;
end $$;
create trigger t_gen_sku before insert on products for each row execute function generate_product_sku();
